A visitor for exceeding canvas (and margin) by a complex command
iis-powp-2022z/powp_jobs2d_projects pull request #18
Opened 2023-01-14 12:53 UTC by jowczar

2023-01-14 13:20 UTC, kowallus requested changes

2023-01-14 13:20 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CommandBoundariesCheckVisitor.java
> +	private final JPanel canvas;
Add CanvasChecker abstraction and JPanel adapter.

2023-01-16 09:22 UTC, kowallus requested changes
This solution can be improved in a few aspects.

2023-01-16 09:22 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CommandBoundariesCheckVisitor.java
> +			isExceedingBoundaries = true;
Such implementation of the visitor is not reusable in run-time. Once flag is set it cannot be unset and following accept calls would always return true. 
To fix this you should set the flag properly (to true or false!) in each visit method (also in visitICompoundCommand)

2023-01-16 09:22 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CommandBoundariesCheckVisitor.java
> +			driverCommand.accept(this);
notice that you can short-cut (break) the visitation if isExceedingBoundaries is set to true.

2023-01-16 09:22 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ICanvas.java
> +	 int getHeight();
Please, do not assume that each canvas wound be rectangular (you can change name to IRectangularCanvas)

2023-01-16 09:22 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CommandBoundariesCheckVisitor.java
> +		if(abs(setPositionCommand.getPosX()) > canvas.getWidth()/2 || abs(setPositionCommand.getPosY()) > canvas.getHeight()/2){
Code duplication. You should apply SRP: checking this condition can be delegated to some strategy.

2023-01-16 17:12 UTC, kowallus requested changes
It is not how the Strategy pattern is implemented. Refactor.

2023-01-16 17:12 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CommandBoundariesCheckVisitor.java
> +	private final IRectangularCanvas canvas;
CommandBoundariesCheckVisitor doesn't need to assume work with rectangular canvas. It is an unnecessary limitation.

2023-01-16 17:12 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CommandBoundariesCheckVisitor.java
> +public class CommandBoundariesCheckVisitor implements Visitor, ICommandBoundariesCheckStrategy{
Implementing ICommandBoundariesCheckStrategy is closer to the Template Method pattern approach. In Strategy pattern ICommandBoundariesCheckStrategy would be an attribute. Please refactor.

2023-01-20 14:33 UTC, jowczar commented
@kowallus
I made a couple of changes.

– I changed it so now check strategy is an actual staregy pattern. It will hold the logic of calculation of canvas, while Visitor only takes care of executing it on every command.

– I also made Visitor accept any canvas as I don't think it should be limited/determined in the visitor

– I deleted IRectangularCanvas as I didn't see further use for it for now. I think all canvas should have width and height (the outermost points in case of shapes) as it may be helpful in future functionalities so I left those getters in ICanvas. 

If they are in a shape of, for example, a star, they can still use RectangularCanvasCheckStrategy to get "box" calculation or somebody can implement FigureCanvasCheckStrategy and calculate exact field of canvas and whether the provided point is out of it. 

If there is a need for any other weird calculation, I think this is the way it is possible to be extended without changes in our code.

– I wasn't sure about naming and placement of the files. I renamed the ICommandBoundairesCheckStrategy to ICanvasBoundariesCheckStrategy. It can be used anywhere, it doesn't have to be a command-related.

– finally, I moved abs() into calculation function.

LMK if anything needs change

2023-01-21 11:19 UTC, kowallus requested changes

2023-01-21 11:19 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ICanvasBoundariesCheckStrategy.java
> +	boolean checkExceedingBoundaries(ICanvas canvas, int X, int Y);
IMO: canvas parameter is not necessary here. ICanvas object can be simply a attribute of ICanvasBoundariesCheckStrategy implementation.

2023-01-21 11:36 UTC, merged