Recording feature
iis-powp-2022z/powp_jobs2d_projects pull request #3
Opened 2022-12-10 15:07 UTC by jowczar

2022-12-13 11:12 UTC, kowallus reviewed
I will wait with merging for "Observer for a driver changes events" task. You will probably need to make minor changes (conflicts, etc.) then.

2022-12-13 11:12 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverManager.java
> +	private final Publisher changePublisher = new Publisher();
Another group is working on "Observer for a driver changes events" so I want to give them a chance to do this task. Therefore, I will wait with merging your solution.

2022-12-13 11:12 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverChangeObserver.java
> +            recordingManager.resumeRecording();
A notification about the recording process and the necessity to substitute a driver would be helpful, eg. "Recording command in progress. To use the driver stop recording."
You can use JOptionPane.

2022-12-17 13:37 UTC, jowczar commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverChangeObserver.java
> +            recordingManager.resumeRecording();
@kowallus  I think now that we use DriverComposite and recording runs in parallel with drawing, this notification becomes obsolete. Is this right?

2022-12-19 13:17 UTC, kowallus requested changes
Nice. I see only one important issue to fix.

2022-12-19 13:17 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverChangeObserver.java
You should find a better name for DriverChangeObserver (such a name suits literally every driver change observer). It doesn't tell anything about its purpose.

2023-01-02 09:38 UTC, merged